//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GigEntry.localhost
{
    using System.Runtime.Serialization;
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.thatindigogirl.com/samples/2006/06")]
    [System.SerializableAttribute()]
    public partial class LinkItem : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
    {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long IdField;
        
        private string TitleField;
        
        private string DescriptionField;
        
        private System.DateTime DateStartField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateEndField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UrlField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                if ((this.IdField.Equals(value) != true))
                {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Title
        {
            get
            {
                return this.TitleField;
            }
            set
            {
                if ((((object)(this.TitleField)) != ((object)(value))))
                {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                if ((((object)(this.DescriptionField)) != ((object)(value))))
                {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public System.DateTime DateStart
        {
            get
            {
                return this.DateStartField;
            }
            set
            {
                if ((this.DateStartField.Equals(value) != true))
                {
                    this.DateStartField = value;
                    this.RaisePropertyChanged("DateStart");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public System.DateTime DateEnd
        {
            get
            {
                return this.DateEndField;
            }
            set
            {
                if ((this.DateEndField.Equals(value) != true))
                {
                    this.DateEndField = value;
                    this.RaisePropertyChanged("DateEnd");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public string Url
        {
            get
            {
                return this.UrlField;
            }
            set
            {
                if ((((object)(this.UrlField)) != ((object)(value))))
                {
                    this.UrlField = value;
                    this.RaisePropertyChanged("Url");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.thatindigogirl.com/samples/2006/06", ConfigurationName="GigEntry.localhost.GigManagerServiceContract", SessionMode=System.ServiceModel.SessionMode.Required)]
    public interface GigManagerServiceContract
    {
        
        // CODEGEN: Generating message contract since the wrapper name (SaveGigRequest) of message SaveGigRequest does not match the default value (SaveGig)
        [System.ServiceModel.OperationContractAttribute(Action="http://www.thatindigogirl.com/samples/2006/06/GigManagerServiceContract/SaveGig", ReplyAction="http://www.thatindigogirl.com/samples/2006/06/GigManagerServiceContract/SaveGigRe" +
            "sponse")]
        GigEntry.localhost.SaveGigResponse SaveGig(GigEntry.localhost.SaveGigRequest request);
        
        // CODEGEN: Generating message contract since the wrapper name (GetGigRequest) of message GetGigRequest does not match the default value (GetGig)
        [System.ServiceModel.OperationContractAttribute(Action="http://www.thatindigogirl.com/samples/2006/06/GigManagerServiceContract/GetGig", ReplyAction="http://www.thatindigogirl.com/samples/2006/06/GigManagerServiceContract/GetGigRes" +
            "ponse")]
        GigEntry.localhost.GetGigResponse GetGig(GigEntry.localhost.GetGigRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SaveGigRequest", WrapperNamespace="http://www.thatindigogirl.com/samples/2006/06", IsWrapped=true)]
    public partial class SaveGigRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.thatindigogirl.com/samples/2006/06", Order=0)]
        public GigEntry.localhost.LinkItem Item;
        
        public SaveGigRequest()
        {
        }
        
        public SaveGigRequest(GigEntry.localhost.LinkItem Item)
        {
            this.Item = Item;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SaveGigResponse", WrapperNamespace="http://www.thatindigogirl.com/samples/2006/06", IsWrapped=true)]
    public partial class SaveGigResponse
    {
        
        public SaveGigResponse()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetGigRequest", WrapperNamespace="http://www.thatindigogirl.com/samples/2006/06", IsWrapped=true)]
    public partial class GetGigRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.thatindigogirl.com/samples/2006/06")]
        public string LicenseKey;
        
        public GetGigRequest()
        {
        }
        
        public GetGigRequest(string LicenseKey)
        {
            this.LicenseKey = LicenseKey;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetGigResponse", WrapperNamespace="http://www.thatindigogirl.com/samples/2006/06", IsWrapped=true)]
    public partial class GetGigResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.thatindigogirl.com/samples/2006/06", Order=0)]
        public GigEntry.localhost.LinkItem Item;
        
        public GetGigResponse()
        {
        }
        
        public GetGigResponse(GigEntry.localhost.LinkItem Item)
        {
            this.Item = Item;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface GigManagerServiceContractChannel : GigEntry.localhost.GigManagerServiceContract, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class GigManagerServiceContractClient : System.ServiceModel.ClientBase<GigEntry.localhost.GigManagerServiceContract>, GigEntry.localhost.GigManagerServiceContract
    {
        
        public GigManagerServiceContractClient()
        {
        }
        
        public GigManagerServiceContractClient(string endpointConfigurationName) : 
                base(endpointConfigurationName)
        {
        }
        
        public GigManagerServiceContractClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public GigManagerServiceContractClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public GigManagerServiceContractClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        GigEntry.localhost.SaveGigResponse GigEntry.localhost.GigManagerServiceContract.SaveGig(GigEntry.localhost.SaveGigRequest request)
        {
            return base.Channel.SaveGig(request);
        }
        
        public void SaveGig(GigEntry.localhost.LinkItem Item)
        {
            GigEntry.localhost.SaveGigRequest inValue = new GigEntry.localhost.SaveGigRequest();
            inValue.Item = Item;
            GigEntry.localhost.SaveGigResponse retVal = ((GigEntry.localhost.GigManagerServiceContract)(this)).SaveGig(inValue);
        }
        
        GigEntry.localhost.GetGigResponse GigEntry.localhost.GigManagerServiceContract.GetGig(GigEntry.localhost.GetGigRequest request)
        {
            return base.Channel.GetGig(request);
        }
        
        public GigEntry.localhost.LinkItem GetGig(string LicenseKey)
        {
            GigEntry.localhost.GetGigRequest inValue = new GigEntry.localhost.GetGigRequest();
            inValue.LicenseKey = LicenseKey;
            GigEntry.localhost.GetGigResponse retVal = ((GigEntry.localhost.GigManagerServiceContract)(this)).GetGig(inValue);
            return retVal.Item;
        }
    }
}
